version: '3.1'

services:

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /home/wuyang/develop/docker_data/redisData:/data # redis data
      - /home/wuyang/develop/docker/redis.conf:/usr/local/etc/redis/redis.conf # redis config
      - /home/wuyang/develop/docker_data/redisLogs:/logs # redis log

  nacos:
    image: nacos/nacos-server:1.4.1
    container_name: nacos-standalone-mysql
    env_file:
      - /home/wuyang/develop/docker/nacos/env/nacos-standlone-mysql.env # 数据库参数配置
    volumes:
      - /home/wuyang/develop/docker_data/nacos/standalone-logs/:/home/nacos/logs  # nacos日志输出
      - /home/wuyang/develop/docker/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties # nacos自定义配置
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - /home/wuyang/develop/docker/nacos/env/mysql.env # mysql env
    volumes:
      - /home/wuyang/develop/docker_data/mysqlData:/var/lib/mysql # mysql data
    ports:
      - "3306:3306"
    restart: always